platform:
  - x64
skip_commits:
  files:
    - "*.yml"
    - "*.rst"
    - "LICENSE"

build: off

install:
  # Install Proxy
  - npm install o_o -g

test_script:
  # Start Proxy
  #- ps: Start-Process -FilePath o_o -NoNewWindow
  - systeminfo
  - mvn test -B -f .\aliyun-java-sdk-core-v5\pom.xml

